codecov:
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "10..70"

  status:
    project:
      default:
        target: auto
        threshold: null
        branches:
          - samantha-dev

        patch:
          default:
            target: auto
            branches:
              - samantha-dev

        
